#!/usr/bin/env python3
"""
update_kali_catalog.py
======================
Fetch the latest Kali Linux VirtualBox release metadata, merge with
curated source inventory, and write:

  - data/kali/vm-releases.json   (machine-readable release list)
  - docs/kali/catalog.md         (human-readable generated catalog)

Usage
-----
  python scripts/kali/update_kali_catalog.py \\
    --output   data/kali/vm-releases.json \\
    --sources  data/kali/sources.json \\
    --catalog  docs/kali/catalog.md \\
    --vbox-dir samples/vbox

Options
-------
  --output    PATH   Destination for updated vm-releases.json
  --sources   PATH   Path to sources.json (read-only)
  --catalog   PATH   Destination for generated catalog.md
  --vbox-dir  PATH   Directory containing optional .vbox sample files
  --dry-run          Parse and print without writing any files
  --verbose          Emit verbose logging
"""

import argparse
import json
import logging
import os
import sys
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import requests
except ImportError:
    requests = None  # type: ignore

LOG_FORMAT = "%(asctime)s  %(levelname)-8s  %(message)s"
logging.basicConfig(level=logging.INFO, format=LOG_FORMAT)
log = logging.getLogger("update_kali_catalog")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

KALI_RELEASE_PAGE = "https://www.kali.org/get-kali/#kali-virtual-machines"
KALI_CDN_BASE = "https://cdimage.kali.org"

# Regex patterns for scraping the Kali downloads page (fallback)
RE_VERSION = re.compile(r"kali-linux-(\d{4}\.\d+)", re.IGNORECASE)
RE_SHA256 = re.compile(r"([a-f0-9]{64})\s+kali-linux-[\w.\-]+\.7z", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_json(path: Path) -> Any:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    log.info("Wrote %s", path)


def fetch_url(url: str, timeout: int = 30) -> str:
    """Return the text content of *url*, or raise RuntimeError."""
    if requests is None:
        raise RuntimeError(
            "The 'requests' library is required. Run: pip install requests"
        )
    resp = requests.get(url, timeout=timeout, headers={"User-Agent": "KALINALYSIS/1.0"})
    resp.raise_for_status()
    return resp.text


def collect_vbox_samples(vbox_dir: Path) -> list[dict]:
    """Scan *vbox_dir* for .vbox files and return minimal metadata stubs."""
    if not vbox_dir.exists():
        return []
    samples = []
    for vbox_file in sorted(vbox_dir.glob("*.vbox")):
        stat = vbox_file.stat()
        samples.append(
            {
                "filename": vbox_file.name,
                "size_bytes": stat.st_size,
                "modified_at": datetime.fromtimestamp(
                    stat.st_mtime, tz=timezone.utc
                ).isoformat(),
            }
        )
    return samples


# ---------------------------------------------------------------------------
# Catalog generation
# ---------------------------------------------------------------------------


def build_catalog_md(releases: list[dict], sources: list[dict], samples: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    lines.append("# KALINALYSIS — Generated Catalog")
    lines.append("")
    lines.append(f"> Auto-generated by `update_kali_catalog.py` on {now}.")
    lines.append("> Do not edit this file manually.")
    lines.append("")

    # ---- VM Releases -------------------------------------------------------
    lines.append("## Kali Linux VirtualBox Releases")
    lines.append("")
    lines.append("| Version | Architecture | Release Date | Size | SHA256 (first 12) | Tags |")
    lines.append("|---|---|---|---|---|---|")
    for r in releases:
        sha_short = r.get("sha256", "")[:12] + "…"
        tags = ", ".join(r.get("tags", []))
        lines.append(
            f"| [{r['version']}]({r['download_url']}) "
            f"| {r['architecture']} "
            f"| {r['release_date']} "
            f"| {r.get('size_human', '–')} "
            f"| `{sha_short}` "
            f"| {tags} |"
        )
    lines.append("")

    # ---- External Sources --------------------------------------------------
    lines.append("## Curated External Sources")
    lines.append("")
    lines.append("| Name | URL | Tags | Mirror | Last Synced |")
    lines.append("|---|---|---|---|---|")
    for s in sources:
        mirror_flag = "✅" if s.get("mirror") else "–"
        last_synced = s.get("last_synced") or "–"
        tags = ", ".join(s.get("tags", []))
        lines.append(
            f"| **{s['name']}** "
            f"| [{s['url']}]({s['url']}) "
            f"| {tags} "
            f"| {mirror_flag} "
            f"| {last_synced} |"
        )
    lines.append("")

    # ---- Local VBox Samples ------------------------------------------------
    if samples:
        lines.append("## Local VBox Samples (`samples/vbox/`)")
        lines.append("")
        lines.append("| Filename | Size | Last Modified |")
        lines.append("|---|---|---|")
        for s in samples:
            lines.append(
                f"| `{s['filename']}` | {s['size_bytes']:,} B | {s['modified_at']} |"
            )
        lines.append("")
    else:
        lines.append("## Local VBox Samples\n\n_No `.vbox` files found in `samples/vbox/`._\n")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update the KALINALYSIS Kali VM release catalog."
    )
    parser.add_argument("--output",   default="data/kali/vm-releases.json")
    parser.add_argument("--sources",  default="data/kali/sources.json")
    parser.add_argument("--catalog",  default="docs/kali/catalog.md")
    parser.add_argument("--vbox-dir", default="samples/vbox")
    parser.add_argument("--dry-run",  action="store_true")
    parser.add_argument("--verbose",  action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.verbose:
        log.setLevel(logging.DEBUG)

    output_path  = Path(args.output)
    sources_path = Path(args.sources)
    catalog_path = Path(args.catalog)
    vbox_dir     = Path(args.vbox_dir)

    # Load existing releases (used as fallback if network unavailable)
    existing_releases: list[dict] = []
    if output_path.exists():
        try:
            existing_data = load_json(output_path)
            existing_releases = existing_data.get("releases", [])
            log.info("Loaded %d existing releases from %s", len(existing_releases), output_path)
        except Exception as exc:
            log.warning("Could not load existing releases: %s", exc)

    # Load sources
    sources_data = load_json(sources_path)
    sources = sources_data.get("sources", [])
    log.info("Loaded %d sources from %s", len(sources), sources_path)

    # Attempt to fetch live release data
    releases = existing_releases
    try:
        log.info("Fetching release page: %s", KALI_RELEASE_PAGE)
        _page_html = fetch_url(KALI_RELEASE_PAGE)
        log.info("Successfully fetched release page (%d chars)", len(_page_html))
        # NOTE: Full HTML parsing would require beautifulsoup4.
        # For now we rely on the curated existing data and note the fetch succeeded.
        log.info("Using curated release data (HTML parsing not yet implemented).")
    except Exception as exc:
        log.warning("Could not fetch live release page (%s); using existing data.", exc)

    # Collect .vbox samples
    samples = collect_vbox_samples(vbox_dir)
    log.info("Found %d local .vbox samples in %s", len(samples), vbox_dir)

    # Build output structures
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    output_data = {
        "_meta": {
            "schema_version": "1.2",
            "generated_by": "update_kali_catalog.py",
            "generated_at": now_iso,
            "source": KALI_RELEASE_PAGE,
        },
        "releases": releases,
    }

    catalog_md = build_catalog_md(releases, sources, samples)

    if args.dry_run:
        log.info("DRY RUN — not writing any files.")
        print(catalog_md)
        return 0

    write_json(output_path, output_data)
    catalog_path.parent.mkdir(parents=True, exist_ok=True)
    catalog_path.write_text(catalog_md, encoding="utf-8")
    log.info("Wrote catalog to %s", catalog_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
