#!/usr/bin/env python3
"""Update Kali VirtualBox release metadata and render curated catalog docs."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin
from urllib.request import Request, urlopen
import xml.etree.ElementTree as ET

DEFAULT_VM_URL = "https://www.kali.org/get-kali/#kali-virtual-machines"
DEFAULT_DOWNLOAD_HOST = "https://cdimage.kali.org"
RELEASE_FILE_RE = re.compile(
    r"(kali-linux-[A-Za-z0-9._-]+-virtualbox-amd64)\.(7z|ova|vbox|vdi|sha256sum|torrent)$"
)


class LinkParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.links: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "a":
            return
        for key, value in attrs:
            if key.lower() == "href" and value:
                self.links.append(value)


def fetch_html(url: str, timeout: int) -> str:
    req = Request(url, headers={"User-Agent": "kali-catalog-updater/1.0"})
    with urlopen(req, timeout=timeout) as response:
        return response.read().decode("utf-8", errors="replace")


def parse_virtualbox_links(html: str, base_url: str) -> list[str]:
    parser = LinkParser()
    parser.feed(html)
    found = set()
    for raw in parser.links:
        absolute = urljoin(base_url, raw)
        file_name = absolute.split("?")[0].split("#")[0].rsplit("/", 1)[-1]
        if RELEASE_FILE_RE.search(file_name):
            found.add(absolute)
        elif "virtualbox-amd64" in raw and raw.startswith("/"):
            found.add(urljoin(DEFAULT_DOWNLOAD_HOST, raw))
    return sorted(found)


def build_release_manifest(links: list[str]) -> list[dict[str, object]]:
    grouped: dict[str, dict[str, object]] = {}
    for link in links:
        clean_link = link.split("?")[0].split("#")[0]
        file_name = clean_link.rsplit("/", 1)[-1]
        match = RELEASE_FILE_RE.search(file_name)
        if not match:
            continue
        release_id = match.group(1)
        artifact_type = match.group(2)
        release = grouped.setdefault(
            release_id,
            {
                "release_id": release_id,
                "label": release_id.replace("kali-linux-", "").replace("-virtualbox-amd64", ""),
                "artifacts": [],
            },
        )
        release["artifacts"].append(
            {
                "type": artifact_type,
                "file_name": file_name,
                "url": clean_link,
            }
        )

    releases: list[dict[str, object]] = []
    for _, release in sorted(grouped.items(), reverse=True):
        release["artifacts"] = sorted(release["artifacts"], key=lambda x: x["file_name"])
        releases.append(release)
    return releases


def parse_vbox_samples(vbox_dir: Path) -> list[dict[str, object]]:
    if not vbox_dir.exists():
        return []

    records: list[dict[str, object]] = []
    for path in sorted(vbox_dir.glob("*.vbox")):
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            records.append({"file": str(path), "error": "invalid XML"})
            continue

        machine = root.find(".//Machine")
        if machine is None:
            records.append({"file": str(path), "error": "missing Machine node"})
            continue

        memory = machine.find(".//Hardware/Memory")
        cpu = machine.find(".//Hardware/CPU")
        attachments = []
        for medium in machine.findall(".//StorageController/AttachedDevice/Image"):
            attachments.append(
                {
                    "uuid": medium.attrib.get("uuid"),
                    "location": medium.attrib.get("location"),
                }
            )

        records.append(
            {
                "file": str(path),
                "machine_name": machine.attrib.get("name"),
                "os_type": machine.attrib.get("OSType"),
                "machine_uuid": machine.attrib.get("uuid"),
                "memory_mb": int(memory.attrib.get("RAMSize", "0")) if memory is not None else None,
                "cpu_count": int(cpu.attrib.get("count", "0")) if cpu is not None else None,
                "attached_images": attachments,
            }
        )

    return records


def render_catalog_markdown(
    output_path: Path,
    source_manifest_path: Path,
    vm_manifest: dict[str, object],
) -> None:
    source_manifest = json.loads(source_manifest_path.read_text(encoding="utf-8"))
    lines = [
        "# Kali Workspace Catalog",
        "",
        "_This file is generated by `scripts/kali/update_kali_catalog.py`._",
        "",
        "## Curated External Sources",
        "",
        "| ID | Name | Type | Focus | URL |",
        "|---|---|---|---|---|",
    ]

    for source in source_manifest.get("sources", []):
        focus = ", ".join(source.get("focus", []))
        lines.append(
            f"| `{source.get('id')}` | {source.get('name')} | {source.get('type')} | {focus} | {source.get('url')} |"
        )

    lines.extend([
        "",
        "## Kali VirtualBox Releases",
        "",
        f"Source page: {vm_manifest.get('source_url')}",
        "",
    ])

    releases = vm_manifest.get("releases", [])
    if releases:
        lines.append("| Release | Artifact Type | Artifact | URL |")
        lines.append("|---|---|---|---|")
        for release in releases:
            release_id = release.get("release_id", "")
            artifacts = release.get("artifacts", [])
            for artifact in artifacts:
                lines.append(
                    f"| `{release_id}` | {artifact.get('type')} | {artifact.get('file_name')} | {artifact.get('url')} |"
                )
    else:
        lines.append("No VirtualBox releases detected in the latest run.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vm-url", default=DEFAULT_VM_URL)
    parser.add_argument("--timeout", type=int, default=30)
    parser.add_argument("--output", default="data/kali/vm-releases.json")
    parser.add_argument("--sources", default="data/kali/sources.json")
    parser.add_argument("--catalog", default="docs/kali/catalog.md")
    parser.add_argument("--vbox-dir", default="samples/vbox")
    parser.add_argument("--offline-html", default=None)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        if args.offline_html:
            html = Path(args.offline_html).read_text(encoding="utf-8")
        else:
            html = fetch_html(args.vm_url, timeout=args.timeout)
    except Exception as exc:
        print(f"Failed to fetch source page: {exc}", file=sys.stderr)
        return 1

    links = parse_virtualbox_links(html, args.vm_url)
    releases = build_release_manifest(links)
    vbox_records = parse_vbox_samples(Path(args.vbox_dir))

    vm_manifest = {
        "schema_version": 1,
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "source_url": args.vm_url,
        "release_count": len(releases),
        "releases": releases,
        "local_vbox_samples": vbox_records,
    }

    if args.dry_run:
        print(json.dumps(vm_manifest, indent=2))
        return 0

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(vm_manifest, indent=2) + "\n", encoding="utf-8")

    render_catalog_markdown(Path(args.catalog), Path(args.sources), vm_manifest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
